apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-handler
  labels:
    app.kubernetes.io/name: webhook-handler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: webhook-handler
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard
  labels:
    app.kubernetes.io/name: admin-dashboard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: admin-dashboard
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine
  labels:
    app.kubernetes.io/name: ai-engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ai-engine
  ports:
    - name: http
      port: 80
      targetPort: http
