/**
 * WCO UI — public entry point.
 *
 * Everything a consumer needs flows from here: tokens (raw + compiled),
 * theme bridges, the component library, and the WCO Motion subsystem.
 */
export * from './tokens';
export * from './design-tokens';
export * from './components';

// ---------------------------------------------------------------------------
// WCO Motion — dependency-free animation + gesture engine.
// ---------------------------------------------------------------------------
// A few motion names collide with the tokens/design-tokens layers above and
// are surfaced here with a `motion*` prefix so both stay importable:
//   - duration      → motionDuration   (design-tokens exports a `duration` record)
//   - EasingName    → motionEasingName (design-tokens exports an `EasingName` type)
//   - Skeleton      → SkeletonLoader   (feedback Skeleton already owns the name)
export {
  // Frame driver
  subscribeFrame,
  pauseFrames,
  resumeFrames,
  setFrameRate,
  getFrameRate,
  __tickFrame,
  __resetFrames,
  __frameCount,
  __setManualFrames,
  // Math + motion value core
  clamp,
  round2,
  mix,
  smoothstep,
  pingpong,
  resolveEasing,
  interpolate,
  interpolateKeyframes,
  resolveDuration,
  MotionValue,
  buildTransform,
  buildFilter,
  buildMotionStyle,
  // Spring / momentum physics
  stepSpring,
  integrateSpring,
  springDuration,
  stepDrop,
  stepFriction,
  flingDistance,
  normalizeVelocity,
  // Motion tokens
  PRINCIPLES,
  DURATIONS,
  duration as motionDuration,
  DISTANCES,
  distance,
  EASINGS,
  SPRINGS,
  spring,
  springSpec,
  PRESETS,
  PRESET_GROUPS,
  resolvePreset,
  presetNames,
  isShakePreset,
  countsOf,
  loopOf,
  // Value + animation hooks and the motion provider
  MotionProvider,
  useMotionPrefs,
  useReducedMotionPref,
  useMotionValue,
  useMotionValueRender,
  binderName,
  useMotionStyle,
  useTween,
  useSpring,
  useSpringFrom,
  useSpringObject,
  timelineValueAt,
  useTimeline,
  useSequence,
  useStagger,
  useInView,
  useCascade,
  useCount,
  useCycle,
  // Pointer / gesture affordances
  useTap,
  useHover,
  useFocus,
  useSwipe,
  usePinch,
  useDrag,
  useMove,
  useRotate,
  useScale,
  useResize,
  // Accessibility guardrails
  REDUCED_MOTION_QUERY,
  getPrefersReducedMotion,
  usePrefersReducedMotion,
  shouldAnimate,
  motionSafeStyle,
  collapseMotion,
  // Framer Motion bridge (pure config adapters — no framer dependency)
  easingToFramer,
  springToFramer,
  loopToFramer,
  transitionToFramer,
  presetToFramer,
  // Scroll-driven primitives
  useScroll,
  useParallax,
  useReveal,
  revealFrom,
  useSticky,
  useScrollSpy,
  useScrolledPast,
  useInfiniteScroll,
  scrollToTarget,
  // Components
  Animate,
  Fade,
  Slide,
  Zoom,
  Flip,
  Rotate,
  Reveal,
  Parallax,
  Spring,
  Tween,
  Timeline,
  Stagger,
  Cascade,
  CountUp,
  SkeletonLoader,
  Ripple,
  Pressable,
  Shake,
  ScrollToTop,
  ScrollProgressBar,
  Sticky,
} from './motion';
export type {
  EasingName as motionEasingName,
  InterpolateOptions,
  MotionStyleValues,
  SpringParams,
  StepResult,
  DropParams,
  DropStep,
  FrictionParams,
  LoopMode,
  SpringSpec,
  PresetSpec,
  Principle,
  DurationToken,
  EasingToken,
  PresetName,
  MotionPrefs,
  MotionProviderProps,
  TweenSpec,
  TweenController,
  SpringHookOptions,
  SpringObjectResult,
  TimelineKeyframe,
  TimelineSpec,
  TimelineController,
  SequenceStep,
  SequenceController,
  StaggerOptions,
  GestureAxis,
  BindHandlers,
  GestureBind,
  TapHandlers,
  TapResult,
  HoverResult,
  FocusResult,
  SwipeDirection,
  SwipeResult,
  PinchResult,
  DragHandlers,
  DragResult,
  MoveResult,
  RotateResult,
  ScaleResult,
  ResizeResult,
  ScrollInfo,
  ScrollOptions,
  ParallaxOptions,
  ParallaxResult,
  RevealDirection,
  RevealOptions,
  RevealResult,
  StickyResult,
  InfiniteScrollOptions,
  InfiniteScrollResult,
  AnimateProps,
  EntryProps,
  SlideDirection,
  SlideProps,
  FlipProps,
  RevealProps,
  ParallaxProps,
  SpringProps,
  TweenProps,
  TimelineProps,
  StaggerProps,
  CascadeProps,
  CountUpProps,
  SkeletonLoaderProps,
  RippleProps,
  PressableProps,
  ShakeProps,
  ScrollToTopProps,
  ScrollProgressBarProps,
  StickyProps,
} from './motion';

// Advanced library foundation helpers
export * from './lib/hooks';
export {
  formatNumber,
  formatCurrency,
  formatPhone,
  formatDate,
  formatRelative,
  parseLocalizedNumber,
  stripNonDigits,
  currencies,
  phoneMetadata,
  type Currency,
} from './lib/format';
export {
  useForm,
  runValidators,
  validators,
  type UseFormOptions,
  type UseFormResult,
  type ValidationRules,
  type Validator,
} from './lib/form';
export { box, type BoxBaseProps } from './lib/polymorphic';
export { sem, semDark, focusRing, motion, controlSize, controlBorderRadius, type ControlSize, type Tone } from './lib/styles';
export { cn } from './lib/cn';