{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wco.fullname" . }}-backend
  labels:
    {{- include "wco.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "wco.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
